spring:
  application:
    name: UserService

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://user-db:5432/user_db
    username: user_user
    password: user_pass



  kafka:
    consumer:
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS} # The consumer will connect to Kafka broker at this address
      auto-offset-reset: earliest # Either earliest, latest or none.
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.value.default.type: com.example.UserService.kafka.EventGet
        spring.json.use.type.headers: false
    producer:
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      acks: -1 # Either 0,1 or -1. -1 waits for all replicas to acknowledge
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer



kafka:
  users-topic: ${KAFKA_USERS_TOPIC}
  users-group-id: ${KAFKA_GROUP_ID}