spring.application.name=demo
#debug=true

spring.datasource.url=jdbc:postgresql://db:5432/pnm_db
spring.datasource.username=pnm
spring.datasource.password=pnm

spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.pattern=%t %m %U %s %b %Dms